### ISSUE TITLE
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed

### ISSUE THREAD

**Issue by vladisavvv** [epam/ai-dial-adapter-openai#66]
Suggested solution from the openai team: https://github.com/openai/openai-python/issues/574#issuecomment-1805027199

The full exception:

```
[31mERROR[0m:    | 2024-02-07 03:28:16 | uvicorn.error | 1 | Exception in ASGI application
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/starlette/responses.py", line 277, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/app/.venv/lib/python3.11/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/app/.venv/lib/python3.11/site-packages/starlette/responses.py", line 250, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 555, in receive
    await self.message_event.wait()
  File "/usr/local/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f7474e81490

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/app/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 419, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/app/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/app/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/app/.venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/app/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
  |     raise exc
  |   File "/app/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/app/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
  |     raise exc
  |   File "/app/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
  |     await self.app(scope, receive, sender)
  |   File "/app/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
  |     raise e
  |   File "/app/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
  |     await self.app(scope, receive, send)
  |   File "/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
  |     await route.handle(scope, receive, send)
  |   File "/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
  |     await self.app(scope, receive, send)
  |   File "/app/.venv/lib/python3.11/site-packages/starlette/routing.py", line 69, in app
  |     await response(scope, receive, send)
  |   File "/app/.venv/lib/python3.11/site-packages/starlette/responses.py", line 270, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/app/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 664, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/app/.venv/lib/python3.11/site-packages/aiohttp/client_proto.py", line 83, in connection_lost
    |     uncompleted = self._parser.feed_eof()
    |                   ^^^^^^^^^^^^^^^^^^^^^^^
    |   File "aiohttp/_http_parser.pyx", line 507, in aiohttp._http_parser.HttpParser.feed_eof
    | aiohttp.http_exceptions.TransferEncodingError: 400, message:
    |   Not enough data for satisfy transfer length header.
    | 
    | The above exception was the direct cause of the following exception:
    | 
    | Traceback (most recent call last):
    |   File "/app/.venv/lib/python3.11/site-packages/starlette/responses.py", line 273, in wrap
    |     await func()
    |   File "/app/.venv/lib/python3.11/site-packages/starlette/responses.py", line 262, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/app/aidial_adapter_openai/utils/sse_stream.py", line 60, in to_openai_sse_stream
    |     async for chunk in stream:
    |   File "/app/aidial_adapter_openai/utils/streaming.py", line 53, in generate_stream
    |     async for chunk in stream:
    |   File "/app/aidial_adapter_openai/utils/streaming.py", line 169, in map_stream
    |     async for item in iterator:
    |   File "/app/.venv/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 232, in <genexpr>
    |     return (
    |            ^
    |   File "/app/.venv/lib/python3.11/site-packages/openai/api_requestor.py", line 396, in wrap_resp
    |     async for r in resp:
    |   File "/app/.venv/lib/python3.11/site-packages/openai/api_requestor.py", line 724, in <genexpr>
    |     return (
    |            ^
    |   File "/app/.venv/lib/python3.11/site-packages/openai/api_requestor.py", line 123, in parse_stream_async
    |     async for line in rbody:
    |   File "/app/.venv/lib/python3.11/site-packages/aiohttp/streams.py", line 44, in __anext__
    |     rv = await self.read_func()
    |          ^^^^^^^^^^^^^^^^^^^^^^
    |   File "/app/.venv/lib/python3.11/site-packages/aiohttp/streams.py", line 307, in readline
    |     return await self.readuntil()
    |            ^^^^^^^^^^^^^^^^^^^^^^
    |   File "/app/.venv/lib/python3.11/site-packages/aiohttp/streams.py", line 341, in readuntil
    |     await self._wait("readuntil")
    |   File "/app/.venv/lib/python3.11/site-packages/aiohttp/streams.py", line 302, in _wait
    |     await waiter
    | aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
    +------------------------------------
```

**Comment by adubovik** [comment]
Resolved by #71
